# Generated by Django 3.0.6 on 2020-05-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='linkimage',
            field=models.CharField(default='na.jpeg', max_length=120),
        ),
        migrations.AddField(
            model_name='family',
            name='otherimages',
            field=models.CharField(default='na.jpeg', max_length=300),
        ),
        migrations.AlterField(
            model_name='family',
            name='spousename',
            field=models.CharField(max_length=100),
        ),
    ]
