# Generated by Django 3.0.6 on 2020-05-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20200522_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=40)),
                ('childid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childid', to='family.Family')),
                ('parentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentid', to='family.Family')),
            ],
        ),
    ]
