# Generated by Django 3.0.6 on 2020-06-01 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_auto_20200527_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyid', models.CharField(max_length=100)),
                ('familyname', models.CharField(max_length=100)),
                ('linkingimage', models.CharField(default='na.jpeg', max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='child',
            name='childid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childid', to='family.Family'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentid', to='family.Family'),
        ),
    ]
