# Generated by Django 3.0.6 on 2020-06-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_auto_20200601_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='familyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='familiesid', to='family.Tree'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='childid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childid', to='family.Family'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentid', to='family.Family'),
        ),
    ]
