# Generated by Django 3.0.6 on 2020-06-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0009_auto_20200601_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='childid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childid', to='family.Family'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentid', to='family.Family'),
        ),
        migrations.AlterField(
            model_name='family',
            name='familyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familesid', to='family.Tree', to_field='familyid'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='familyid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
