# Generated by Django 3.0.6 on 2020-06-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0011_auto_20200601_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='fathername',
            field=models.CharField(default='Void', max_length=100),
        ),
        migrations.AddField(
            model_name='family',
            name='mothername',
            field=models.CharField(default='Void', max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='childid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childid', to='family.Family'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentid', to='family.Family'),
        ),
    ]
